/// ***LOCALHOST***
### Get All Products
GET http://localhost:8080/store

### Get One Product
GET http://localhost:8080/store/63dea7756986c1acdd0f1d79

### List Product
POST http://localhost:8080/store HTTP/1.1
content-type: application/json

{
    "title":"Localhost Sample Product",
    "qty":300,
    "description":"Product description",
    "price":5.99,
    "rating":0.47
}

### API Documentation
GET http://localhost:8080/api-docs

/// ***PRODUCTION***
### Get All Products
GET https://cse341-dwbb.onrender.com/store

### Get One Product
GET https://cse341-dwbb.onrender.com/store/63dea7756986c1acdd0f1d79

### List Product
POST https://cse341-dwbb.onrender.com/store HTTP/1.1
content-type: application/json

{
    "title":"Production Sample Product",
    "qty":200,
    "description":"Product description",
    "price":6.99,
    "rating":0.77
}

### API Documentation
GET https://cse341-dwbb.onrender.com/api-docs