/// ***LOCALHOST***
### Get All Products
GET http://localhost:8080/products

### Get One Product
GET http://localhost:8080/products/63e5acaec2ea13c357f654e5

### Get One Account
GET http://localhost:8080/account/63e596a2249a26406b261c19

### List Product
POST http://localhost:8080/products HTTP/1.1
content-type: application/json

{
    "title":"Localhost Sample Product",
    "qty":300,
    "description":"Product description",
    "price":5.99,
    "rating":0.47
}

### List Product (Should Fail Data Validation)
POST http://localhost:8080/products HTTP/1.1
content-type: application/json

{
    "title":304,
    "qty":"Twenty One",
    "description":1.1,
    "price":"Free 99",
    "rating":"Good"
}

### Create Account
POST http://localhost:8080/account HTTP/1.1
content-type: application/json

{
    "username": "example_username",
    "actualName":  "Name Namison",
    "email" : "name@example.com",
    "password": "3x4mp1e_P455w0rd!",
    "items": [],
    "privileges": 1
}

### Create Account (Should Fail Data Validation)
POST http://localhost:8080/account HTTP/1.1
content-type: application/json

{
    "username": 700,
    "actualName":  1.1,
    "email" : 6.8,
    "password": [],
    "items": "a pink horsey",
    "privileges": "one"
}

### Update Product Listing
POST http://localhost:8080/products HTTP/1.1
content-type: application/json

{
    "title":"Updated Localhost Product",
    "qty":300,
    "description":"Updated product description.",
    "price":5.99,
    "rating":0.47
}

### Update Account
POST http://localhost:8080/account HTTP/1.1
content-type: application/json

{
    "username": "xX_Jane1984_Xx",
    "actualName":  "Jane Jameson",
    "email" : "jane@example.com",
    "password": "jAn3s_Password!",
    "items": [],
    "privileges": 1
}

### Delete Product
DELETE http://localhost:8080/products/63e7317c03d9815d20a41429

### Delete Account
DELETE http://localhost:8080/account/63e596a2249a26406b261c19

### API Documentation
GET http://localhost:8080/api-docs

/// ***PRODUCTION***

### Get All Products
GET https://cse341-b.onrender.com/products

### Get One Product
GET https://cse341-b.onrender.com/products/63e5acaec2ea13c357f654e5

### Get One Account
GET https://cse341-b.onrender.com/account/63e596a2249a26406b261c19

### List Product
POST https://cse341-b.onrender.com/products HTTP/1.1
content-type: application/json

{
    "title":"Production Sample Product",
    "qty":300,
    "description":"Product description",
    "price":5.99,
    "rating":0.47
}

### List Product (Should Fail Data Validation)
POST https://cse341-b.onrender.com/products HTTP/1.1
content-type: application/json

{
    "title":304,
    "qty":"Twenty One",
    "description":1.1,
    "price":"Free 99",
    "rating":"Good"
}

### Create Account
POST https://cse341-b.onrender.com/account HTTP/1.1
content-type: application/json

{
    "username": "example_username",
    "actualName":  "Name Namison",
    "email" : "name@example.com",
    "password": "3x4mp1e_P455w0rd!",
    "items": [],
    "privileges": 1
}

### Create Account (Should Fail Data Validation)
POST https://cse341-b.onrender.com/account HTTP/1.1
content-type: application/json

{
    "username": 700,
    "actualName":  1.1,
    "email" : 6.8,
    "password": [],
    "items": "a pink horsey",
    "privileges": "one"
}

### Update Product Listing
POST https://cse341-b.onrender.com/products HTTP/1.1
content-type: application/json

{
    "title":"Updated Production Product",
    "qty":300,
    "description":"Updated product description.",
    "price":5.99,
    "rating":0.47
}

### Update Account
POST https://cse341-b.onrender.com/products HTTP/1.1
content-type: application/json

{
    "username": "xX_Jane1984_Xx",
    "actualName":  "Jane Jameson",
    "email" : "jane@example.com",
    "password": "jAn3s_Password!",
    "items": [],
    "privileges": 1
}

### Delete Product
DELETE https://cse341-b.onrender.com/63e596a2249a26406b261c1b

### Delete Account
DELETE https://cse341-b.onrender.com/account/63e596a2249a26406b261c19

### API Documentation
GET https://cse341-b.onrender.com/api-docs